# Generated by Django 3.2.5 on 2021-07-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ofert_activity', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('rating', models.FloatField(max_length=1)),
                ('type_actvity', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('schedule', models.DateTimeField()),
                ('duration_activity', models.DateTimeField()),
                ('department', models.CharField(max_length=30)),
                ('municipality', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id_hosting', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=25)),
                ('municipality', models.CharField(default=None, max_length=30)),
                ('rating', models.FloatField(max_length=1)),
                ('price_per_night', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id_municipality', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=255)),
                ('desciption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ofert',
            fields=[
                ('id_ofert', models.IntegerField(primary_key=True, serialize=False)),
                ('in_ofert', models.DateField()),
                ('end_ofert', models.DateField()),
                ('discount', models.FloatField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id_tourist', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ofert_site', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('municipality', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('rating', models.FloatField(max_length=1)),
                ('schedule', models.DateTimeField()),
                ('tipe_site_touristic', models.CharField(max_length=30)),
                ('id_municipality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_restaurant', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ofert_restaurant', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('department', models.CharField(default=None, max_length=30)),
                ('municipality', models.CharField(max_length=30)),
                ('schedule', models.DateTimeField()),
                ('rating', models.FloatField(max_length=1)),
                ('type_food', models.CharField(max_length=30)),
                ('municipality_restaurant', models.ManyToManyField(to='core.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('hour_reservation', models.DateTimeField(auto_now=True)),
                ('duration_reservation', models.DateTimeField(auto_now=True)),
                ('id_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('id_hosting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.hosting')),
                ('id_ofert', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ofert')),
                ('id_restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
                ('id_tourist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.tourist')),
                ('id_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='hosting',
            name='id_municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id_discovery', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('rating', models.FloatField(max_length=1)),
                ('description', models.TextField()),
                ('id_municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='id_municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
    ]
