# Generated by Django 3.2.5 on 2021-07-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id_ofert_activity',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id_ofert_restaurant',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='id_ofert_site',
        ),
        migrations.AddField(
            model_name='activity',
            name='id_ofert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ofert'),
        ),
        migrations.AddField(
            model_name='hosting',
            name='id_ofert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ofert'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id_ofert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ofert'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='id_ofert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ofert'),
        ),
    ]
