# Generated by Django 3.2.5 on 2021-07-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210709_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofert',
            name='end_ofert',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ofert',
            name='in_ofert',
            field=models.CharField(max_length=30),
        ),
    ]
