# Generated by Django 3.2.5 on 2021-07-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tourist_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='schedule',
            field=models.CharField(max_length=30),
        ),
    ]
