# Generated by Django 3.2.5 on 2021-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activity_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_activity',
            field=models.CharField(max_length=30),
        ),
    ]
