# Generated by Django 3.2.5 on 2021-07-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_activity_duration_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='schedule',
            field=models.CharField(max_length=30),
        ),
    ]
