# Generated by Django 3.2.5 on 2021-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_restaurant_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration_reservation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hour_reservation',
            field=models.CharField(max_length=30),
        ),
    ]
