# Generated by Django 3.2.5 on 2021-07-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210714_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_hosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hosting'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_ofert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ofert'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_reservation',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tourist'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
